version: 1
kind: ct
enabled: false
vmid: null
name: forgejo
hostname: forgejo
node: 4core
tags:
  - 99-terra-dev
network:
  mode: static
  address: 192.168.99.22/24
  gateway: 192.168.99.1
resources:
  cpu_cores: 2
  memory_mb: 1024
  swap_mb: 1024
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 12
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/forgejo
services:
  - name: forgejo
    scheme: http
    port: 3000
    traefik_tag: traefik-int
    traefik_label: forgejo
    uri: forgejo.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
