version: 1
kind: ct
enabled: true
vmid: null
name: mediaserver
hostname: mediaserver
node: n100
tags:
  - 99-terra-dev
network:
  segment: vlan-99
  mode: dhcp
resources:
  cpu_cores: 2
  memory_mb: 4096
  swap_mb: 1024
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rdb
  rootfs_size_gb: 32
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/mediaserver
    - slot: 1
      mp: /mnt/downloads
      storage: /mnt/pve/downloads
    - slot: 2
      mp: /mnt/multimedia
      storage: /mnt/pve/media
services:
  - name: jellyfin
    scheme: http
    port: 8096
    traefik_tag: traefik-int
    traefik_label: jellyfin
    uri: jellyfin.lbtec.org
  - name: jellyseer
    scheme: http
    port: 5055
    traefik_tag: traefik-int
    traefik_label: jellyseer
    uri: jellyseer.lbtec.org
  - name: sonarr
    scheme: http
    port: 8989
    traefik_tag: traefik-int
    traefik_label: sonarr
    uri: sonarr.lbtec.org
  - name: radarr
    scheme: http
    port: 7878
    traefik_tag: traefik-int
    traefik_label: radarr
    uri: radarr.lbtec.org
  - name: lidarr
    scheme: http
    port: 8686
    traefik_tag: traefik-int
    traefik_label: lidarr
    uri: lidarr.lbtec.org
  - name: bazarr
    scheme: http
    port: 6767
    traefik_tag: traefik-int
    traefik_label: bazarr
    uri: bazarr.lbtec.org
  - name: prowlarr
    scheme: http
    port: 9696
    traefik_tag: traefik-int
    traefik_label: prowlarr
    uri: prowlarr.lbtec.org
  - name: flaresolverr
    scheme: http
    port: 8191
    traefik_tag: traefik-int
    traefik_label: flaresolverr
    uri: flaresolverr.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
