version: 1
kind: ct
enabled: false
vmid: null
name: miniaps
hostname: miniaps
node: n100
tags:
  - 99-terra-dev
network:
  segment: vlan-99
  mode: dhcp
resources:
  cpu_cores: 2
  memory_mb: 4096
  swap_mb: 1024
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 32
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/miniaps
services:
  - name: miniaps
    scheme: http
    port: 80
    traefik_tag: traefik-int
    traefik_label: miniaps
    uri: miniaps.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
