version: 1
kind: ct
enabled: true
vmid: null
name: ntfy
hostname: ntfy
node: 2core
tags:
  - 99-terra-dev
network:
  mode: dhcp
resources:
  cpu_cores: 1
  memory_mb: 512
  swap_mb: 512
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 4
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/ntfy
services:
  - name: ntfy
    scheme: http
    port: 80
    traefik_tag: traefik-int
    traefik_label: ntfy
    uri: ntfy.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
