version: 1
kind: ct
enabled: false
vmid: null
name: ntpong
hostname: ntpong
node: 4core
tags:
  - 99-terra-dev
network:
  segment: vlan-35
  mode: static
  address: 192.168.35.77/24
  gateway: 192.168.35.1
resources:
  cpu_cores: 2
  memory_mb: 8196
  swap_mb: 2048
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 32
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/ntpong
services:
  - name: ntpong
    scheme: http
    port: 6500
    traefik_tag: traefik-int
    traefik_label: ntpong
    uri: ntpong.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
