version: 1
kind: ct
enabled: false
vmid: null
name: proxy-ext
hostname: proxy-ext
node: 2core
tags:
  - 99-terra-dev
network:
  segment: vlan-50
  mode: static
  address: 192.168.50.201/24
  gateway: 192.168.50.1
resources:
  cpu_cores: 2
  memory_mb: 2048
  swap_mb: 1024
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 8
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/proxy-ext
services:
  - name: proxy-ext
    scheme: http
    port: 8080
    traefik_tag: traefik-int
    traefik_label: proxy-ext
    uri: proxy-ext.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
