version: 1
kind: ct
enabled: true
vmid: null
name: rdtclient
hostname: rdtclient
node: 4core
tags:
  - 99-terra-dev
network:
  segment: vlan-99
  mode: dhcp
resources:
  cpu_cores: 2
  memory_mb: 4096
  swap_mb: 1024
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: ceph-rbd
  rootfs_size_gb: 32
lxc:
  template: local:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst
  unprivileged: true
  features:
    nesting: true
  mounts:
    - slot: 0
      mp: /mnt/data
      storage: /mnt/pve/nas1/data/dev/rdtclient
    - slot: 1
      mp: /mnt/downloads
      storage: /mnt/pve/downloads
    - slot: 2
      mp: /mnt/multimedia
      storage: /mnt/pve/media
services:
  - name: rdtclient
    scheme: http
    port: 6500
    traefik_tag: traefik-int
    traefik_label: rdtclient
    uri: rdtclient.lbtec.org
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
