boot:
  on_boot: true
  start: true
enabled: true
hostname: testedhcp
kind: ct
lxc:
  features:
    nesting: true
  features_manual: {}
  mounts:
    - mp: /mnt/data
      slot: 0
      storage: /mnt/pve/nas1/data/dev/testedhcp
  template: local:vztmpl/debian-11-standard_11.7-1_amd64.tar.zst
  unprivileged: true
name: testedhcp
network:
  mode: dhcp
  segment: internal
node: 6core
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
qemu:
  agent_enabled: false
  kvm_enabled: false
resources:
  cpu_cores: 2
  memory_mb: 2048
  swap_mb: 1024
services:
  - name: rdtclient
    port: 6500
    scheme: http
    traefik_label: rdtclient
    traefik_tag: traefik-int
    uri: testerdt.lbtec.org
storage:
  rootfs_size_gb: 4
  rootfs_storage: local
tags:
  - testedhcp
version: 1
vmid: null
