version: 1
networks:
  vlan-99:
    bridge: vmbr0
    cidr: 192.168.99.0/24
    gateway: 192.168.99.1
    dns_servers: []
    dns_domain: lbtec.org
  servicos-externos:
    bridge: vmbr0
    cidr: 192.168.99.0/24
    gateway: 192.168.99.1
    dns_servers:
      - 192.168.99.1
    dns_domain: lbtec.org
  vlan-17:
    bridge: vmbr0
    cidr: 192.168.99.0/24
    gateway: 192.168.99.1
    dns_servers:
      - 192.168.99.1
    dns_domain: lbtec.org
