version: 1
kind: vm
enabled: false
vmid: null
name: rdtclient
node: n100
tags:
  - 99-terra-dev
network:
  segment: vlan-99
  mode: dhcp
resources:
  cpu_cores: 1
  cpu_sockets: 1
  memory_mb: 1024
boot:
  on_boot: false
  start_state: running
storage:
  rootfs_storage: local
  rootfs_size_gb: 3
qemu:
  sockets: 1
  agent_enabled: false
  kvm_enabled: false
  scsi_hardware: virtio-scsi-pci
  disks: []
services: []
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
