version: 1
kind: ct
enabled: true
vmid: 6011
name: homarr
hostname: homarr
node: pve
tags:
  - 60-servicos-externos
network:
  segment: vlan-99
  mode: dhcp
resources:
  cpu_cores: 1
  memory_mb: 512
  swap_mb: 0
boot:
  on_boot: true
  start: true
storage:
  rootfs_storage: local-lvm
  rootfs_size_gb: 4
lxc:
  unprivileged: true
  features:
    nesting: true
  mounts: []
services: []
operations:
  ansible_enabled: false
  backup_policy: null
  bootstrap_profile: null
